# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-10 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('account', models.IntegerField(primary_key=True, serialize=False, verbose_name='账号')),
                ('nickname', models.CharField(max_length=11, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
