# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(verbose_name='卡号')),
                ('money', models.IntegerField(verbose_name='充值金额')),
                ('tim', models.CharField(max_length=50, verbose_name='充值时间')),
            ],
            options={
                'db_table': 'rechar',
            },
        ),
    ]
