# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-11 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rechar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(verbose_name='卡号')),
                ('money', models.IntegerField(verbose_name='消费金额')),
                ('tim', models.CharField(max_length=50, verbose_name='消费时间')),
            ],
        ),
    ]
